define({
    error: 'GHG QA/QC Error',
    button_label: 'Todos los datos',
    groups: 'Grupos',
    domains: 'Sector',
    subdomains: 'Sub-Sector',
    areas: 'Áreas',
    items: 'Artículos',
    item: 'Artículo',
    elements: 'Elementos',
    ghg: 'Gases de Efecto Invernadero',
    ghg_overview: 'Panorama Regional',
    ghg_quality: 'GC-CC y Verificacion',
    ghg_indicators: 'Indicadores',
    ghg_data: 'Datos Georreferenciados',
    please_select: 'Seleccionar...',
    please_select_option: 'Seleccionar una opción',
    verification: 'Verificacion',
    qa_qc: 'SG/CQ',
    gt: 'Agricultura total',
    ge: 'Fermentación entérica',
    gm: 'Gestión del estiércol',
    gr: 'Cultivo del arroz',
    gy: 'Fertilizantes sintéticos',
    gu: 'Estiércol aplicado a los suelos',
    gp: 'Estiércol animal aplicado a los suelos',
    ga: 'Residuos agrícolas',
    gv: 'Cultivación de suelos orgánicos',
    gb: 'Combustión - residuos agrícolas',
    gh: 'Combustión - Sabana',
    gn: 'Use de energía',
    gl: 'Uso de la tierra total',
    gf: 'Tierras forestales',
    gc: 'Tierras de cultivo',
    gg: 'Pastizales',
    gi: 'Combustión de biomasa',
    gas: 'Suelos agrícolas',
    ag_soils: 'Suelos agrícolas',
    charts: 'Gráficos',
    tables: 'Tablas',
    emissions: 'Emisiones (Gg CO2eq)',
    emissions_activity: 'Dato de actividad',
    emissions_factor: 'Factor de emisión implícito (unidades)',
    data_not_available: 'Datos No Disponible',
    faostat: 'FAOSTAT',
    nc: 'Datos Nacionales',
    difference: 'Diferencia (Datos Nacionales / FAOSTAT)',
    norm_difference: 'Diferencia normalizada (Datos Nacionales / FAOSTAT)',
    code: 'Código',
    category: 'Categoría',
    agriculture: 'Agricultura',
    land_use: 'Uso de la tierra',
    direct_soil_emissions: 'Emisiones directas del suelo',
    pasture_paddock_manure: 'Estiércol depositado en pastura/prado/pradera',
    indirect_emissions: 'Emisiones indirectas',
    co2eq: '(Emisiones Gg CO2eq)',
    table_selector_label: 'Tipo de Tabla',
    export_data_label: 'Exportar Datos',
    buffaloes: 'Búfalos',
    cattle_dairy: 'Vacas lecheras',
    cattle_non_dairy: 'Vacunos, otros',
    goats: 'Caprinos',
    horses: 'Caballos',
    sheep: 'Ovinos',
    camels_llamas: 'Camélidos y Llamas',
    mules_asses: 'Mulas y Asnos',
    swine: 'Porcinos',
    poultry_birds: 'Aves de corral',
    rice: 'Arroz, cascara',
    maize: 'Maiz',
    sugar_cane: 'Azucar, caña',
    wheat: 'Trigo',
    mu: {
        ge: 'Existencias [Cabeza]',
        gm: 'Existencias [Cabeza]',
        gr: 'Área cosechada [Ha]',
        gh: 'Superficie quemada [Ha]',
        gb: 'Biomasa quemada [tonnes]'
    },
    page_under_construction: 'Pagina en construcción. Nos disculpas por las molestias.',
    instructions: 'Seleccione el país y el sector.<br>La herramienta mostrará una serie de resultados en formato gráfico y tabular.',
    here: 'aquí',
    user_guide: 'Guía del usuario',

    other_direct_emissions: "Otras Emisiones Directas",
    n_fixing_crops: "Cultivos fijadores del nitrógeno",
    other: "Otras",

    from_ch4_and_n2o: "proveniente de CH<sub>4</sub>, proveniente de N<sub>2</sub>O",
    from_ch4: "proveniente de CH<sub>4</sub>",

    contextButtonTitle: "Gráfico imprimir/exportar",
    downloadJPEG: "Descargar JPG",
    downloadPDF: "Descargar PNG",
    downloadPNG: "Descargar documento en PDF",
    downloadSVG: "Descargar SVG",
    printChart: "Gráfico imprimir/exportar",
    resetZoom: "Restabl. zoom",
    resetZoomTitle: "Restablecer el zoom 1:1"

});