define({
    error: 'GHG QA/QC Error',
    button_label: 'Bulk Downloads',
    groups: 'Groupe',
    domains: 'Domaine',
    subdomains: 'Sub-Domaine',
    areas: 'Zone Geographique',
    items: 'Articles',
    item: 'Produit',
    elements: 'Elements',
    ghg: 'Gaz a Effet de Serre',
    ghg_overview: 'Aperçu Regional',
    ghg_quality: 'AQ-CQ et Verification',
    ghg_indicators: 'Indicateurs',
    ghg_data: 'Donnees Georeferencees',
    please_select: 's\'il vous plait selectionnez...',
    please_select_option: 'Selectionnez une option',
    verification: 'Verification',
    qa_qc: 'AQ/CQ',
    gt: 'Agriculture total',
    ge: 'Fermentation entérique',
    gm: 'Gestion du fumier',
    gr: 'Riziculture',
    gy: 'Engrais synthétique',
    gu: 'Fumier appliquée aux sols',
    gp: 'Fumier animal appliqué aux sols',
    ga: 'Résidus de récoltes',
    gv: 'Cultivation of histosols',
    gb: 'Combustion - résidus de récoltes',
    gh: 'Combustion - Savane',
    gn: 'Consommation d\'énergie',
    gl: 'Utilisation des terres total',
    gf: 'Terres forestières',
    gc: 'Terres cultivées',
    gg: 'Prairie',
    gi: 'Combustion - Biomasse',
    gas: 'Sols agricoles',
    ag_soils: 'Sols agricoles',
    charts: 'Graphiques',
    tables: 'Tableaux',
    emissions: 'Émissions (Gg CO2eq)',
    emissions_activity: 'Données d’Activité',
    emissions_factor: 'Implicite Facteur d\'émission (unités)',
    data_not_available: 'Données Non Disponibles',
    faostat: 'FAOSTAT',
    nc: 'Données Nationales',
    difference: 'Différence (Données Nationales / FAOSTAT)',
    norm_difference: 'Différence Normalisée (Données Nationales / FAOSTAT)',
    code: 'Code',
    category: 'Catégorie',
    agriculture: 'Agriculture',
    land_use: 'Utilization des terres',
    direct_soil_emissions: 'Émissions directes des sols',
    pasture_paddock_maure: 'Fumier déposé sur des pâturages/parcours/parcelles',
    indirect_emissions: 'Émissions indirectes',
    co2eq: '(Émissions Gg CO2eq)',
    table_selector_label: 'Type de Tableau',
    export_data_label: 'Exporter des Données',
    buffaloes: 'Buffles',
    cattle_dairy: 'Bovins, vaches laitières',
    cattle_non_dairy: 'Bovins, autres',
    goats: 'Caprins',
    horses: 'Chevaux',
    sheep: 'Ovins',
    camels_llamas: 'Chameaux et Lamas',
    mules_asses: 'Mules et Anes',
    swine: 'Suidés',
    poultry_birds: 'Volaille',
    rice: 'Riz, Paddy',
    maize: 'Maïs',
    sugar_cane: 'Sucre, canne',
    wheat: 'Blé',
    mu: {
        ge: 'Réserves [Tête]',
        gm: 'Réserves [Tête]',
        gr: 'Surface cultivée [Ha]',
        gh: 'Superficie brûlé [Ha]',
        gb: 'Biomasse brûlé [tonnes]'
    },
    page_under_construction: 'Page en construction. Nous excusons pour tout inconvénient.',
    instructions: 'Sélectionnez un pays et le secteur.<br>L\'outil fournira une série de résultats au format graphique et tabulaire.',
    here: 'ici',
    user_guide: 'Guide de l\'utilisateur',


    other_direct_emissions: "Other Direct Emissions",
    n_fixing_crops: "N-Fixing Crops",
    from_ch4_and_n2o: "venant de CH<sub>4</sub>, venant de N<sub>2</sub>O",
    from_ch4: "From CH<sub>4</sub>",

    contextButtonTitle: "Imprimez/Exportez graphique",
    downloadJPEG: "Imprimez graphique, Téléchargez image PNG/JPEG",
    downloadPDF: "Téléchargez document PDF",
    downloadPNG: "Téléchargez PNG",
    downloadSVG: "Téléchargez image vectorielle SVG",
    printChart: "Imprimez/Exportez graphique",
    resetZoom: "Réinit. zoom",
    resetZoomTitle: "Réinitialiser zoom 1:1"

});