define({
    error: 'GHG QA/QC Error',
    button_label: 'Todos los datos',
    groups: 'Grupos',
    domains: 'Dominios',
    subdomains: 'Sub-Dominios',
    areas: 'Areas',
    items: 'Articulos',
    item: 'Articulo',
    elements: 'Elementos',
    ghg: 'Gases de Efecto Invernadero',
    ghg_overview: 'Panorama Regional',
    ghg_quality: 'GC-CC y Verificacion',
    ghg_indicators: 'Indicadores',
    ghg_data: 'Datos Georreferenciados',
    please_select: 'Por Favor Seleccione...',
    verification: 'Verificacion',
    qa_qc: 'SG/CQ',
    gt: 'Agricultura total',
    ge: 'Fermentación entérica',
    gm: 'Gestión del estiércol',
    gr: 'Cultivo del arroz',
    gy: 'Fertilizantes sintéticos',
    gu: 'Estiércol aplicado a los suelos',
    gp: 'Estiércol animal aplicado a los suelos',
    ga: 'Residuos agrícolas',
    gv: 'Cultivation of histosols',
    gb: 'Combustión - residuos agrícolas',
    gh: 'Combustión - Sabana',
    gn: 'Use de energía',
    gl: 'Uso de la tierra total',
    gf: 'Tierras forestales',
    gc: 'Tierras de cultivo',
    gg: 'Pastizales',
    gi: 'Combustión de biomasa',
    ag_soils: 'Suelos agrícolas',
    charts: 'Gráficos',
    tables: 'Tablas',
    emissions: 'Emisiones (Gg CO2eq)',
    emissions_activity: 'Dato de actividad',
    emissions_factor: 'Factor de emisión implícito (unidades)',
    data_not_available: 'Datos No Disponible',
    faostat: 'FAOSTAT',
    nc: 'Comunicación Nacional',
    difference: 'Diferencia (Comunicación Nacional - FAOSTAT)',
    norm_difference: 'Diferencia normalizada (Comunicación Nacional - FAOSTAT)',
    code: 'Código',
    category: 'Categoría',
    agriculture: 'Agricultura',
    land_use: 'Land Use',
    direct_soil_emissions: 'Emisiones directas del suelo',
    pasture_paddock_maure: 'Estiércol depositado en pastura/prado/pradera',
    indirect_emissions: 'Emisiones indirectas',
    co2eq: '(Emisiones Gg CO2eq)',
    table_selector_label: 'Tipo de Tabla',
    export_data_label: 'Exportar Datos',
    buffaloes: 'Búfalos',
    cattle_dairy: 'Vacas lecheras',
    cattle_non_dairy: 'Vacunos, otros',
    goats: 'Caprinos',
    horses: 'Caballos',
    sheep: 'Ovinos',
    camels_llamas: 'Camélidos y Llamas',
    mules_asses: 'Mulas y Asnos',
    swine: 'Porcinos',
    poultry_birds: 'Aves de corral',
    rice: 'Arroz, cascara',
    maize: 'Maiz',
    sugar_cane: 'Azucar, caña',
    wheat: 'Trigo',
    mu: {
        ge: 'Existencias [Cabeza]',
        gm: 'Estiércol [Kg]',
        gr: 'Área cosechada [Ha]',
        gh: 'Superficie quemada [Ha]',
        gb: 'Biomasa quemada [tonnes]'
    }
});