define({
    root : {
        error: 'GHG QA/QC Error',
        button_label: 'Bulk Downloads',
        groups : 'Groups',
        domains : 'Sector',
        subdomains : 'Sub-Sectors',
        areas : 'Geographic Areas',
        items : 'Items',
        item : 'Item',
        elements : 'Elements',
        ghg: 'Greenhouse Gases',
        ghg_overview: 'Regional Overview',
        ghg_quality: 'QA-QC and Verification',
        ghg_indicators: 'Indicators',
        ghg_data: 'Georeferenced Data',
        please_select: 'Select...',
        verification: 'Verification',
        qa_qc: 'QA/QC',
        gt: 'Agriculture Total',
        ge: 'Enteric Fermentation',
        gm: 'Manure Management',
        gr: 'Rice Cultivation',
        gy: 'Synthetic Fertilizers',
        gu: 'Manure applied to Soils',
        gp: 'Animal manure applied to soils',
        ga: 'Crop Residues',
        gv: 'Cultivation of histosols',
        gb: 'Burning - Crop Residues',
        gh: 'Burning - Savanna',
        gn: 'Energy Use',
        gl: 'Land Use Total',
        gf: 'Forest Land',
        gc: 'Cropland',
        gg: 'Grassland',
        gi: 'Burning - Biomass',
        gas: 'Agricultural Soils',
        charts: 'Charts',
        tables: 'Tables',
        emissions: 'Emissions (Gg CO<sub>2</sub>eq)',
        emissions_activity: 'Activity data',
        emissions_factor: 'Implied Emission Factor (Units)',
        data_not_available: 'Data Not Available',
        faostat: 'FAOSTAT',
        nc: 'National Communication',
        difference: 'Difference (National Communication - FAOSTAT)',
        norm_difference: 'Normalized Difference (National Communication - FAOSTAT)',
        code: 'Code',
        category: 'Category',
        agriculture: 'Agriculture',
        land_use: 'Land Use',
        direct_soil_emissions: 'Direct Soil Emissions',
        pasture_paddock_manure: 'Pasture, Range and Paddock Manure',
        indirect_emissions: 'Indirect Emissions',
        co2eq: '(Emissions Gg CO<sub>2</sub>eq)',
        table_selector_label: 'Table Type',
        export_data_label: 'Export Data',
        buffaloes: 'Buffaloes',
        cattle_dairy: 'Cattle, dairy',
        cattle_non_dairy: 'Cattle, non-dairy',
        goats: 'Goats',
        horses: 'Horses',
        sheep: 'Sheep',
        camels_llamas: 'Camels and Llamas',
        mules_asses: 'Mules and Asses',
        swine: 'Swine',
        poultry_birds: 'Poultry Birds',
        rice: 'Rice, Paddy',
        maize: 'Maize',
        sugar_cane: 'Sugar Cane',
        wheat: 'Wheat',
        mu: {
            ge: 'Stocks [Head]',
            gm: 'Manure [Kg]',
            gr: 'Area harvested [Ha]',
            gh: 'Burned area [Ha]',
            gb: 'Biomass burned [tonnes]'
        },
        page_under_construction: 'Page under construction. We apologies for any inconvenience.',
        instructions: 'Start by selecting the country and the sector.<br>The tool will return a series of results in graphical and tabular format.<br>For more information, a user instruction guide is available',
        here: 'here',
        user_guide: 'User instruction guide'
    },
    fr : true,
    es : true,
    S : true,
    F : true
});